// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Generates a personalized tagline for a portfolio's hero section.
 *
 * - generateTagline - A function that generates a tagline.
 * - GenerateTaglineInput - The input type for the generateTagline function.
 * - GenerateTaglineOutput - The return type for the generateTagline function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateTaglineInputSchema = z.object({
  name: z.string().describe('The name of the person the portfolio is for.'),
  skills: z.string().describe('A comma separated list of skills.'),
  style: z.string().describe('Desired tone/style of the tagline (e.g., professional, creative, minimalist).'),
});
export type GenerateTaglineInput = z.infer<typeof GenerateTaglineInputSchema>;

const GenerateTaglineOutputSchema = z.object({
  tagline: z.string().describe('A personalized tagline for the portfolio hero section.'),
});
export type GenerateTaglineOutput = z.infer<typeof GenerateTaglineOutputSchema>;

export async function generateTagline(input: GenerateTaglineInput): Promise<GenerateTaglineOutput> {
  return generateTaglineFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateTaglinePrompt',
  input: {schema: GenerateTaglineInputSchema},
  output: {schema: GenerateTaglineOutputSchema},
  prompt: `You are an expert at creating compelling taglines for online portfolios.

  Given the following information, generate a short, impactful, and personalized tagline for the portfolio's hero section. The tagline should be tailored to the individual's name, skills, and desired style.

  Name: {{{name}}}
  Skills: {{{skills}}}
  Style: {{{style}}}
  `,
});

const generateTaglineFlow = ai.defineFlow(
  {
    name: 'generateTaglineFlow',
    inputSchema: GenerateTaglineInputSchema,
    outputSchema: GenerateTaglineOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
